import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Privacy Policy | MarketPilot AI", description: "How MarketPilot processes and protects information for Quantify Terminal." };

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" summary="This policy explains what the private MarketPilot workspace processes, why it is used, and how connected-account data can be controlled.">
    <section><h2>1. Scope</h2><p>MarketPilot is a private, single-owner marketing operations tool used for Quantify Terminal. This policy covers the public website, owner workspace, and integrations configured by the owner.</p></section>
    <section><h2>2. Information processed</h2><p>MarketPilot may store startup profile details, campaign strategies, generated drafts, lead contact details and consent status, SEO audit results, publishing records, integration status, and security or audit logs. When social accounts are connected, OAuth access and refresh tokens, account identifiers, and token expiry information may also be stored.</p><p>If media features are enabled, uploaded files and technical metadata such as format, size, dimensions, duration, and provider asset identifiers may be processed.</p></section>
    <section><h2>3. How information is used</h2><p>Information is used to create owner-requested marketing material, manage campaigns and leads, run SEO checks, send consent-based email, publish content only after approval, maintain integrations, secure the service, and diagnose operational failures. MarketPilot does not sell personal information or use connected-account data for unrelated advertising.</p></section>
    <section><h2>4. Service providers</h2><p>Depending on configuration, information may be processed by Vercel, Render, Neon, OpenRouter or another configured AI provider, Brevo, Cloudinary, X, LinkedIn, Meta/Instagram, and Reddit. Each provider processes information under its own terms and privacy policy. Only information needed for the requested operation is sent.</p></section>
    <section><h2>5. AI and social integrations</h2><p>Startup context and draft instructions may be sent to the configured AI provider to generate content. Generated content is not automatically trusted and remains subject to owner review. Social tokens are kept server-side and encrypted at rest; provider secrets are not intentionally exposed in browser JavaScript.</p></section>
    <section><h2>6. Retention and deletion</h2><p>Workspace records are retained while needed to operate the private service or until the owner deletes them. Integration tokens are removed when an integration is disconnected, subject to provider behavior and backup retention. Content already published to a third-party platform may remain there until removed through that platform.</p><p>See the <a href="/data-deletion">Data Deletion Instructions</a> for removal and access-revocation steps.</p></section>
    <section><h2>7. Security</h2><p>MarketPilot uses owner authentication, server-side secret handling, encrypted social tokens, HTTPS in production, and approval gates before publishing. No internet service can guarantee absolute security; compromised credentials should be revoked immediately.</p></section>
    <section><h2>8. Your choices</h2><p>The owner can edit or delete operational records, disconnect providers, and revoke MarketPilot from provider account settings. Requests concerning access, correction, or deletion can be submitted through <a href="/support">Support</a>. Do not include passwords, API keys, access tokens, or unnecessary personal information in a support request.</p></section>
    <section><h2>9. Children and changes</h2><p>MarketPilot is not directed to children under 13 and is not intended to collect their personal information. Material policy updates will be posted on this page with a revised effective date.</p></section>
  </LegalPage>;
}
